### ISSUE TITLE
Infinite process loop and auto detection of Audio language selection

### ISSUE THREAD

**Issue by Gillous** [serpafi/TAO-MKV#1]
Hi!

I stumble upon your software and I love it already.

I tried it and observed a strange behavior: when muxing a set of files, the process is starting again after finishing the list. Hence, it looks like an infinite loop.

Also, I have this MKV file with dual audio that are named in English; My software is in French and when I select to only keep a specific language, it get rids of all of them (Japanese to keep; while English and Japanese are presents; "Japonais" selected = no remaining language after muxing). Is there a way to autodetect the languages within the file list to avoid this behavior? Any workaround?

Best!

Gilles

**Comment by serpafi** [comment]
hi Gilles.
Above all, I am delighted that you like my software.

I was already aware of these problems and I fixed them in the new version "V3" that I am preparing.

I also add the OCR detection for the subtitles of several languages, a complete update (software, components, etc ...),
detection of audio languages ​​including tracks without language info and many other things "the list is a bit long".

it will be necessary to be patient for the V3 but I work on it every day.

in the meantime, do not hesitate to contact me for other questions, opinions, suggestions.

PS: I go through google translate FR => EN, sorry for the mistakes.

Gilles

**Comment by Gillous** [comment]
Salut! Déjà, si tu parles français, c'est un bon point pour nous deux ;-)

Excellent, j'attends la V3 avec impatience, car le batch remux est d'une puissance impressionnante pour mon utilisation. Encore merci d'avoir écrit un script de ce calibre!

Très bonne continuation et bon courage pour terminer le code!

A bientôt, 

Gilles

**Comment by serpafi** [comment]
La V3 sera bien plus puissant et efficace avec plus d'options.
Pour l'heure, j'ai fini la partie visuelle et je réécris les processus pour corriger plusieurs erreurs.

Merci pour tes encouragements :-)
à tantôt

**Comment by serpafi** [comment]
Bonjour/bonsoir Gilles,
Dans la description j'ai rajouté des infos sur le développement du logiciel, cela te fera une idée du développement.
(Mise à jour régulière)
Sinon quelques petites questions,
Comment as-tu découvert TAO-MKV?
Quelle utilisation as-tu?
As-tu des suggestions d'options ou autres fonctionnalités? 
Merci de ton retour et de ta patience :-)

**Comment by Gillous** [comment]
Salut Serpafi!
Parfait, hâte que la V3 sorte! Je suis tombé sur tes scripts à l'aide de Google, qui m'a orienté vers un thread qui présentait ton logiciel. J'avais vraiment besoin de traiter en lot mes fichiers en dual audio, pour lesquels je souhaitais enlever l'Anglais et garder le Japonais; histoire de gagner de la place et d'éviter de changer à chaque fois la langue dans Plex.

Pour mes besoins, c'est du traitement en lot où je personnalise les conteneurs MKV ou MP4: enlever une langue audio, sélectionner les pistes par défaut, ajouter des sous titres (même si je préfère fonctionner en .srt en externe). Donc que du muxing; pas d'encodage.

L'idée de pouvoir choisir l'exacte langue audio déterminée automatiquement par ton logiciel serait fabuleux; mais je comprends aussi que si on met des fichiers dont les annotations de langues sont différentes, cela peut représenter une difficulté dans la façon de présenter les choix à l'utilisateur.

Pour mes MP4, j'utilise aussi un autre logiciel (MP4 Video & Audio Tag Editor) qui me permets de les tagger pour ajouter une affiche et récupérer les infos de films. Assez sympa, même si le workflow implique de travailler film par film. Pour les MKV, je passe par JRIVER qui va directement et en masse me cherche les infos de films et affiches (mais stockés dans des fichiers annexes: JPG & XML). D'ailleurs, je renomme mes fichiers vidéos avec JRIVER pour un formatage aisé.

Je ne pense pas que ton logiciel devrait faire tout ça, mais pour éditer les conteneurs en masse de type MKV ou MP4, c'est déjà une ultime avancée.

Par ailleurs, j'ai pu constater que parfois, même en demandant de garder les sous titres, on ne les récupère pas après muxage... Petit problème à corriger.

J'espère t'aider dans la description de mes besoins, et je te soutiens (moralement) dans ton développement, car je crois que beaucoup de monde y gagnerait à utiliser les fruits de ton développement !

**Comment by serpafi** [comment]
Merci pour ton retour.
Je suis content qu'on puisse me découvrir via google :-)

Il y aura une fonctionnalité qui répondra, je pense, à tes attentes.
 Une sauvegarde/chargement des préférences.
- Mettre les audios jpn ou fre par exemple, en piste par défaut, même fonction pour les sub.
- pistes, extension, encodage vidéo/audio, etc... préférées

Sur la partie édition par lot, ça pourra peut-être se faire mais pas tout de suite (assez complexe) mais 

Sinon pour info, j'avance plus vite que prévu, donc je pourrai proposer une bêta sous peu.
Il y aura des fonctionnalités bloquées mais pour ton utilisation, ça sera bon.
Pour les soucis des sub et audio, c'est déjà réglé dans la V3 puisque je réécris, stabilise et accélère 100% de mon code.

Tu m'aides beaucoup dans tes descriptions et ton soutien, ça me donne des idées d'évolutions futur.

N’hésites pas à m'envoyer des idées ou autres car depuis la naissance de TAO-MKV le 14/10/2019,
mon but est de créer le logiciel le plus complet du marche pay et free tout en restant gratuit
et si tu le souhaites, parles-en autour de toi ;-)

Au fait, tu peux m'appeler Gilles au lieu de Serpafi.
Bonne journée et à tantôt

**Comment by Gillous** [comment]
Salut!

Je vois que le projet avance! c'est une bonne nouvelle!!!

je te souhaite, ainsqi qu'à ton équipe, une bonne année!

A bientôt, 

Gilles (oui on a le même prénom)

**Comment by serpafi** [comment]
Salut,
Oui ça avance bien et la version nightly sort sous peu.
Je dois corriger un petit bug sur l'annonce et la Maj auto donc sortie officiel aujourd'hui ou demain ;)
Je te souhaite aussi une bonne année et comme mon équipe est composée que de moi, le souhait est déjà transmis   :'D

Bonne journée et à tantôt
